### PR TITLE
release 0.3.0

### PR DESCRIPTION
**Pull request by bcliang**
- fix: non-US locale support
- fix: handle OCVCURVE table data
- add: tests

### CODE REVIEW

**Comment by bcliang** [comment]
closes #15

**Comment by bcliang** [comment]
.. pushed to pypi. I want to go back to take a look at why the package doesn't just use pandas.from_csv()? See impl. example with the ocv curve.

**Comment by p2jones** [comment]
Good question. I assumed there was a reason not to use from_csv().

I introduced a bug in gamryparser.py with nonnumeric_keys. The key 'Pt' should be `int`, but is currently kept as `str`. 

[Lines 226-229](https://github.com/bcliang/gamry-parser/blob/04bec7891a1d979301d60e3902a0adae4afde34e/gamry_parser/gamryparser.py#L226-L229) should be replaced with:
```
                for key in curve_keys:
                    nonnumeric_keys = ['Over',]
                    if key in nonnumeric_keys:
                        continue
                    elif key == 'Pt':
                        temp.index = temp.index.map(int)
                    else:
                        temp[key] = temp[key].map(locale.atof)
```

**Comment by bcliang** [comment]
> Good question. I assumed there was a reason not to use from_csv().
> 
> I introduced a bug in gamryparser.py with nonnumeric_keys. The key 'Pt' should be `int`, but is currently kept as `str`.
> 
> [Lines 226-229](https://github.com/bcliang/gamry-parser/blob/04bec7891a1d979301d60e3902a0adae4afde34e/gamry_parser/gamryparser.py#L226-L229) should be replaced with:
> 
> ```
>                 for key in curve_keys:
>                     nonnumeric_keys = ['Over',]
>                     if key in nonnumeric_keys:
>                         continue
>                     elif key == 'Pt':
>                         temp.index = temp.index.map(int)
>                     else:
>                         temp[key] = temp[key].map(locale.atof)
> ```

Made a quick fix and pushed version 0.3.1 to pypi

**Pull request merged**
